/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javah */

#ifndef _Included_javah
#define _Included_javah
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javah
 * Method:    show
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javah_show
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
