/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javah */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javah
 * Method:    show
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javah_gen_sdf(JNIEnv *env, jobject obj, jstring path){
    int len = (*env)->GetStringLength(env, path);
    char* p = (char*)malloc()
}

#ifdef __cplusplus
}
