/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Controller */

#ifndef _Included_Controller
#define _Included_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Controller
 * Method:    gen_sdf
 * Signature: ([IIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_Controller_gen_1sdf
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
